import { ToolData } from "../types/tools";

// Tool data structured with conceptual reference to:
// - Battery/Electric/Pneumatic: radtorque.com ecosystem (RAD series)
// - Hydraulic: torsionx.com, HexPro, MaxDRV, PWRPAX systems
// Ranges and capabilities reflect actual product specifications.

export const TOOL_DATA: ToolData[] = [
  // B-RAD Standard Series
  {
    id: "b-rad-300",
    name: "B-RAD 300",
    category: "battery_torque_tool",
    torqueRange: { min: 135, max: 300 },
    accuracy: "±5%",
    weightClass: "medium",
    typicalApplications: ["structural", "plant_maintenance"],
    industries: ["mining", "oil_gas", "manufacturing", "railway", "wind_energy"],
    powerSource: "battery",
    rentalFit: "high",
    notes: ["Reaction arm required.", "Not intended for critical clamp-load joints."],
    accuracyPriorityFit: "standard"
  },
  {
    id: "b-rad-600",
    name: "B-RAD 600",
    category: "battery_torque_tool",
    torqueRange: { min: 200, max: 600 },
    accuracy: "±5%",
    weightClass: "medium",
    typicalApplications: ["structural", "plant_maintenance"],
    industries: ["mining", "oil_gas", "manufacturing", "railway", "wind_energy"],
    powerSource: "battery",
    rentalFit: "high",
    notes: ["Reaction arm required.", "Not intended for critical clamp-load joints."],
    accuracyPriorityFit: "standard"
  },
  {
    id: "b-rad-900",
    name: "B-RAD 900",
    category: "battery_torque_tool",
    torqueRange: { min: 300, max: 900 },
    accuracy: "±5%",
    weightClass: "medium",
    typicalApplications: ["structural", "flange", "plant_maintenance"],
    industries: ["mining", "oil_gas", "manufacturing", "railway", "wind_energy"],
    powerSource: "battery",
    rentalFit: "high",
    notes: ["Reaction arm required.", "Not intended for critical clamp-load joints."],
    accuracyPriorityFit: "standard"
  },
  {
    id: "b-rad-1200",
    name: "B-RAD 1200",
    category: "battery_torque_tool",
    torqueRange: { min: 400, max: 1200 },
    accuracy: "±5%",
    weightClass: "medium",
    typicalApplications: ["structural", "flange", "plant_maintenance"],
    industries: ["mining", "oil_gas", "manufacturing", "railway", "wind_energy"],
    powerSource: "battery",
    rentalFit: "high",
    notes: ["Reaction arm required.", "Not intended for critical clamp-load joints."],
    accuracyPriorityFit: "standard"
  },
  {
    id: "b-rad-1500",
    name: "B-RAD 1500",
    category: "battery_torque_tool",
    torqueRange: { min: 500, max: 1500 },
    accuracy: "±5%",
    weightClass: "medium",
    typicalApplications: ["structural", "flange", "plant_maintenance"],
    industries: ["mining", "oil_gas", "manufacturing", "railway", "wind_energy"],
    powerSource: "battery",
    rentalFit: "high",
    notes: ["Reaction arm required.", "Not intended for critical clamp-load joints."],
    accuracyPriorityFit: "standard"
  },
  {
    id: "b-rad-2000",
    name: "B-RAD 2000",
    category: "battery_torque_tool",
    torqueRange: { min: 700, max: 2000 },
    accuracy: "±5%",
    weightClass: "medium",
    typicalApplications: ["structural", "flange", "plant_maintenance"],
    industries: ["mining", "oil_gas", "manufacturing", "railway", "wind_energy"],
    powerSource: "battery",
    rentalFit: "high",
    notes: ["Reaction arm required.", "Not intended for critical clamp-load joints."],
    accuracyPriorityFit: "standard"
  },
  {
    id: "b-rad-3000",
    name: "B-RAD 3000",
    category: "battery_torque_tool",
    torqueRange: { min: 1000, max: 3000 },
    accuracy: "±5%",
    weightClass: "medium",
    typicalApplications: ["structural", "flange", "plant_maintenance"],
    industries: ["mining", "oil_gas", "manufacturing", "railway", "wind_energy"],
    powerSource: "battery",
    rentalFit: "high",
    notes: ["Reaction arm required.", "Not intended for critical clamp-load joints."],
    accuracyPriorityFit: "standard"
  },
  {
    id: "b-rad-5000",
    name: "B-RAD 5000",
    category: "battery_torque_tool",
    torqueRange: { min: 1500, max: 5000 },
    accuracy: "±5%",
    weightClass: "medium",
    typicalApplications: ["structural", "flange", "plant_maintenance"],
    industries: ["mining", "oil_gas", "manufacturing", "railway", "wind_energy"],
    powerSource: "battery",
    rentalFit: "high",
    notes: ["Reaction arm required.", "Not intended for critical clamp-load joints."],
    accuracyPriorityFit: "standard"
  },
  // B-RAD Xtreme Series
  {
    id: "b-rad-xtreme-3000",
    name: "B-RAD Xtreme 3000",
    category: "battery_torque_tool",
    torqueRange: { min: 1000, max: 3000 },
    accuracy: "±5%",
    weightClass: "medium",
    typicalApplications: ["structural", "flange"],
    industries: ["mining", "oil_gas", "manufacturing", "railway", "wind_energy"],
    powerSource: "battery",
    rentalFit: "high",
    notes: ["Reaction arm required.", "Xtreme series for demanding applications."],
    accuracyPriorityFit: "standard"
  },
  {
    id: "b-rad-xtreme-6000",
    name: "B-RAD Xtreme 6000",
    category: "battery_torque_tool",
    torqueRange: { min: 2000, max: 6000 },
    accuracy: "±5%",
    weightClass: "medium",
    typicalApplications: ["structural", "flange"],
    industries: ["mining", "oil_gas", "manufacturing", "railway", "wind_energy"],
    powerSource: "battery",
    rentalFit: "high",
    notes: ["Reaction arm required.", "Xtreme series for demanding applications."],
    accuracyPriorityFit: "standard"
  },
  {
    id: "b-rad-xtreme-9000",
    name: "B-RAD Xtreme 9000",
    category: "battery_torque_tool",
    torqueRange: { min: 3000, max: 9000 },
    accuracy: "±5%",
    weightClass: "medium",
    typicalApplications: ["structural", "flange"],
    industries: ["mining", "oil_gas", "manufacturing", "railway", "wind_energy"],
    powerSource: "battery",
    rentalFit: "high",
    notes: ["Reaction arm required.", "Xtreme series for demanding applications."],
    accuracyPriorityFit: "standard"
  },
  // DB-RAD High-Torque Series
  {
    id: "db-rad-700",
    name: "DB-RAD 700",
    category: "battery_torque_tool",
    torqueRange: { min: 300, max: 700 },
    accuracy: "±5%",
    weightClass: "heavy",
    typicalApplications: ["flange"],
    industries: ["mining", "oil_gas"],
    powerSource: "battery",
    rentalFit: "high",
    notes: ["Heavier than B-RAD.", "High-torque battery tooling."],
    accuracyPriorityFit: "standard"
  },
  {
    id: "db-rad-1000",
    name: "DB-RAD 1000",
    category: "battery_torque_tool",
    torqueRange: { min: 400, max: 1000 },
    accuracy: "±5%",
    weightClass: "heavy",
    typicalApplications: ["flange"],
    industries: ["mining", "oil_gas"],
    powerSource: "battery",
    rentalFit: "high",
    notes: ["Heavier than B-RAD.", "High-torque battery tooling."],
    accuracyPriorityFit: "standard"
  },
  {
    id: "db-rad-1500",
    name: "DB-RAD 1500",
    category: "battery_torque_tool",
    torqueRange: { min: 600, max: 1500 },
    accuracy: "±5%",
    weightClass: "heavy",
    typicalApplications: ["flange"],
    industries: ["mining", "oil_gas"],
    powerSource: "battery",
    rentalFit: "high",
    notes: ["Heavier than B-RAD.", "High-torque battery tooling."],
    accuracyPriorityFit: "standard"
  },
  {
    id: "db-rad-2000",
    name: "DB-RAD 2000",
    category: "battery_torque_tool",
    torqueRange: { min: 800, max: 2000 },
    accuracy: "±5%",
    weightClass: "heavy",
    typicalApplications: ["flange"],
    industries: ["mining", "oil_gas"],
    powerSource: "battery",
    rentalFit: "high",
    notes: ["Heavier than B-RAD.", "High-torque battery tooling."],
    accuracyPriorityFit: "standard"
  },
  {
    id: "db-rad-4000",
    name: "DB-RAD 4000",
    category: "battery_torque_tool",
    torqueRange: { min: 1500, max: 4000 },
    accuracy: "±5%",
    weightClass: "heavy",
    typicalApplications: ["flange"],
    industries: ["mining", "oil_gas"],
    powerSource: "battery",
    rentalFit: "high",
    notes: ["Heavier than B-RAD.", "High-torque battery tooling."],
    accuracyPriorityFit: "standard"
  },
  {
    id: "db-rad-6000",
    name: "DB-RAD 6000",
    category: "battery_torque_tool",
    torqueRange: { min: 2000, max: 6000 },
    accuracy: "±5%",
    weightClass: "heavy",
    typicalApplications: ["flange"],
    industries: ["mining", "oil_gas"],
    powerSource: "battery",
    rentalFit: "high",
    notes: ["Heavier than B-RAD.", "High-torque battery tooling."],
    accuracyPriorityFit: "standard"
  },
  {
    id: "db-rad-8000",
    name: "DB-RAD 8000",
    category: "battery_torque_tool",
    torqueRange: { min: 3000, max: 8000 },
    accuracy: "±5%",
    weightClass: "heavy",
    typicalApplications: ["flange"],
    industries: ["mining", "oil_gas"],
    powerSource: "battery",
    rentalFit: "high",
    notes: ["Heavier than B-RAD.", "High-torque battery tooling."],
    accuracyPriorityFit: "standard"
  },
  {
    id: "db-rad-11000",
    name: "DB-RAD 11000",
    category: "battery_torque_tool",
    torqueRange: { min: 4000, max: 11000 },
    accuracy: "±5%",
    weightClass: "heavy",
    typicalApplications: ["flange"],
    industries: ["mining", "oil_gas"],
    powerSource: "battery",
    rentalFit: "high",
    notes: ["Heavier than B-RAD.", "High-torque battery tooling.", "Hydraulic preferred above upper range."],
    accuracyPriorityFit: "standard"
  },
  // V-RAD Inline/Vertical Series (Battery)
  {
    id: "v-rad-300",
    name: "V-RAD 300",
    category: "battery_torque_tool",
    torqueRange: { min: 100, max: 300 },
    accuracy: "±5%",
    weightClass: "light",
    typicalApplications: ["structural"],
    industries: ["aerospace"],
    powerSource: "battery",
    rentalFit: "high",
    notes: ["Tight access applications.", "Limited torque capacity.", "Non-critical joints only."],
    accuracyPriorityFit: "standard"
  },
  {
    id: "v-rad-600",
    name: "V-RAD 600",
    category: "battery_torque_tool",
    torqueRange: { min: 200, max: 600 },
    accuracy: "±5%",
    weightClass: "light",
    typicalApplications: ["structural"],
    industries: ["aerospace"],
    powerSource: "battery",
    rentalFit: "high",
    notes: ["Tight access applications.", "Limited torque capacity.", "Non-critical joints only."],
    accuracyPriorityFit: "standard"
  },
  {
    id: "v-rad-900",
    name: "V-RAD 900",
    category: "battery_torque_tool",
    torqueRange: { min: 300, max: 900 },
    accuracy: "±5%",
    weightClass: "light",
    typicalApplications: ["structural"],
    industries: ["aerospace"],
    powerSource: "battery",
    rentalFit: "high",
    notes: ["Tight access applications.", "Limited torque capacity.", "Non-critical joints only."],
    accuracyPriorityFit: "standard"
  },
  {
    id: "v-rad-1200",
    name: "V-RAD 1200",
    category: "battery_torque_tool",
    torqueRange: { min: 400, max: 1200 },
    accuracy: "±5%",
    weightClass: "light",
    typicalApplications: ["structural"],
    industries: ["aerospace"],
    powerSource: "battery",
    rentalFit: "high",
    notes: ["Tight access applications.", "Limited torque capacity.", "Non-critical joints only."],
    accuracyPriorityFit: "standard"
  },
  {
    id: "v-rad-2000",
    name: "V-RAD 2000",
    category: "battery_torque_tool",
    torqueRange: { min: 700, max: 2000 },
    accuracy: "±5%",
    weightClass: "light",
    typicalApplications: ["structural"],
    industries: ["aerospace"],
    powerSource: "battery",
    rentalFit: "high",
    notes: ["Tight access applications.", "Limited torque capacity.", "Non-critical joints only."],
    accuracyPriorityFit: "standard"
  },
  // E-RAD Standard Series
  {
    id: "e-rad-300",
    name: "E-RAD 300",
    category: "electric_torque_tool",
    torqueRange: { min: 100, max: 300 },
    accuracy: "±3%",
    weightClass: "medium",
    typicalApplications: ["plant_maintenance"],
    industries: ["manufacturing", "aerospace", "refineries"],
    powerSource: "electric",
    rentalFit: "high",
    notes: ["Requires power source.", "Suitable for QA-driven environments."],
    accuracyPriorityFit: "high"
  },
  {
    id: "e-rad-600",
    name: "E-RAD 600",
    category: "electric_torque_tool",
    torqueRange: { min: 200, max: 600 },
    accuracy: "±3%",
    weightClass: "medium",
    typicalApplications: ["plant_maintenance"],
    industries: ["manufacturing", "aerospace", "refineries"],
    powerSource: "electric",
    rentalFit: "high",
    notes: ["Requires power source.", "Suitable for QA-driven environments."],
    accuracyPriorityFit: "high"
  },
  {
    id: "e-rad-900",
    name: "E-RAD 900",
    category: "electric_torque_tool",
    torqueRange: { min: 300, max: 900 },
    accuracy: "±3%",
    weightClass: "medium",
    typicalApplications: ["plant_maintenance"],
    industries: ["manufacturing", "aerospace", "refineries"],
    powerSource: "electric",
    rentalFit: "high",
    notes: ["Requires power source.", "Suitable for QA-driven environments."],
    accuracyPriorityFit: "high"
  },
  {
    id: "e-rad-1200",
    name: "E-RAD 1200",
    category: "electric_torque_tool",
    torqueRange: { min: 400, max: 1200 },
    accuracy: "±3%",
    weightClass: "medium",
    typicalApplications: ["plant_maintenance"],
    industries: ["manufacturing", "aerospace", "refineries"],
    powerSource: "electric",
    rentalFit: "high",
    notes: ["Requires power source.", "Suitable for QA-driven environments."],
    accuracyPriorityFit: "high"
  },
  {
    id: "e-rad-2000",
    name: "E-RAD 2000",
    category: "electric_torque_tool",
    torqueRange: { min: 700, max: 2000 },
    accuracy: "±3%",
    weightClass: "medium",
    typicalApplications: ["plant_maintenance"],
    industries: ["manufacturing", "aerospace", "refineries"],
    powerSource: "electric",
    rentalFit: "high",
    notes: ["Requires power source.", "Suitable for QA-driven environments."],
    accuracyPriorityFit: "high"
  },
  {
    id: "e-rad-3000",
    name: "E-RAD 3000",
    category: "electric_torque_tool",
    torqueRange: { min: 1000, max: 3000 },
    accuracy: "±3%",
    weightClass: "medium",
    typicalApplications: ["plant_maintenance"],
    industries: ["manufacturing", "aerospace", "refineries"],
    powerSource: "electric",
    rentalFit: "high",
    notes: ["Requires power source.", "Suitable for QA-driven environments."],
    accuracyPriorityFit: "high"
  },
  {
    id: "e-rad-5000",
    name: "E-RAD 5000",
    category: "electric_torque_tool",
    torqueRange: { min: 1500, max: 5000 },
    accuracy: "±3%",
    weightClass: "medium",
    typicalApplications: ["plant_maintenance"],
    industries: ["manufacturing", "aerospace", "refineries"],
    powerSource: "electric",
    rentalFit: "high",
    notes: ["Requires power source.", "Suitable for QA-driven environments."],
    accuracyPriorityFit: "high"
  },
  {
    id: "e-rad-8000",
    name: "E-RAD 8000",
    category: "electric_torque_tool",
    torqueRange: { min: 2500, max: 8000 },
    accuracy: "±3%",
    weightClass: "medium",
    typicalApplications: ["plant_maintenance"],
    industries: ["manufacturing", "aerospace", "refineries"],
    powerSource: "electric",
    rentalFit: "high",
    notes: ["Requires power source.", "Suitable for QA-driven environments."],
    accuracyPriorityFit: "high"
  },
  // E-RAD BLU Data-Capable Series
  {
    id: "e-rad-blu-300",
    name: "E-RAD BLU 300",
    category: "electric_torque_tool",
    torqueRange: { min: 100, max: 300 },
    accuracy: "±3% or better",
    weightClass: "medium",
    typicalApplications: ["turbine"],
    industries: ["aerospace", "petrochemical", "refineries", "wind_energy"],
    powerSource: "electric",
    rentalFit: "high",
    notes: ["Data logging capable.", "Verify hazardous-area suitability before use."],
    accuracyPriorityFit: "critical"
  },
  {
    id: "e-rad-blu-600",
    name: "E-RAD BLU 600",
    category: "electric_torque_tool",
    torqueRange: { min: 200, max: 600 },
    accuracy: "±3% or better",
    weightClass: "medium",
    typicalApplications: ["turbine"],
    industries: ["aerospace", "petrochemical", "refineries", "wind_energy"],
    powerSource: "electric",
    rentalFit: "high",
    notes: ["Data logging capable.", "Verify hazardous-area suitability before use."],
    accuracyPriorityFit: "critical"
  },
  {
    id: "e-rad-blu-900",
    name: "E-RAD BLU 900",
    category: "electric_torque_tool",
    torqueRange: { min: 300, max: 900 },
    accuracy: "±3% or better",
    weightClass: "medium",
    typicalApplications: ["turbine"],
    industries: ["aerospace", "petrochemical", "refineries", "wind_energy"],
    powerSource: "electric",
    rentalFit: "high",
    notes: ["Data logging capable.", "Verify hazardous-area suitability before use."],
    accuracyPriorityFit: "critical"
  },
  {
    id: "e-rad-blu-1200",
    name: "E-RAD BLU 1200",
    category: "electric_torque_tool",
    torqueRange: { min: 400, max: 1200 },
    accuracy: "±3% or better",
    weightClass: "medium",
    typicalApplications: ["turbine"],
    industries: ["aerospace", "petrochemical", "refineries", "wind_energy"],
    powerSource: "electric",
    rentalFit: "high",
    notes: ["Data logging capable.", "Verify hazardous-area suitability before use."],
    accuracyPriorityFit: "critical"
  },
  {
    id: "e-rad-blu-2000",
    name: "E-RAD BLU 2000",
    category: "electric_torque_tool",
    torqueRange: { min: 700, max: 2000 },
    accuracy: "±3% or better",
    weightClass: "medium",
    typicalApplications: ["turbine"],
    industries: ["aerospace", "petrochemical", "refineries", "wind_energy"],
    powerSource: "electric",
    rentalFit: "high",
    notes: ["Data logging capable.", "Verify hazardous-area suitability before use."],
    accuracyPriorityFit: "critical"
  },
  {
    id: "e-rad-blu-3000",
    name: "E-RAD BLU 3000",
    category: "electric_torque_tool",
    torqueRange: { min: 1000, max: 3000 },
    accuracy: "±3% or better",
    weightClass: "medium",
    typicalApplications: ["turbine"],
    industries: ["aerospace", "petrochemical", "refineries", "wind_energy"],
    powerSource: "electric",
    rentalFit: "high",
    notes: ["Data logging capable.", "Verify hazardous-area suitability before use."],
    accuracyPriorityFit: "critical"
  },
  {
    id: "e-rad-blu-5000",
    name: "E-RAD BLU 5000",
    category: "electric_torque_tool",
    torqueRange: { min: 1500, max: 5000 },
    accuracy: "±3% or better",
    weightClass: "medium",
    typicalApplications: ["turbine"],
    industries: ["aerospace", "petrochemical", "refineries", "wind_energy"],
    powerSource: "electric",
    rentalFit: "high",
    notes: ["Data logging capable.", "Verify hazardous-area suitability before use."],
    accuracyPriorityFit: "critical"
  },
  {
    id: "e-rad-blu-8000",
    name: "E-RAD BLU 8000",
    category: "electric_torque_tool",
    torqueRange: { min: 2500, max: 8000 },
    accuracy: "±3% or better",
    weightClass: "medium",
    typicalApplications: ["turbine"],
    industries: ["aerospace", "petrochemical", "refineries", "wind_energy"],
    powerSource: "electric",
    rentalFit: "high",
    notes: ["Data logging capable.", "Verify hazardous-area suitability before use."],
    accuracyPriorityFit: "critical"
  },
  {
    id: "e-rad-blu-11000",
    name: "E-RAD BLU 11000",
    category: "electric_torque_tool",
    torqueRange: { min: 4000, max: 11000 },
    accuracy: "±3% or better",
    weightClass: "medium",
    typicalApplications: ["turbine"],
    industries: ["aerospace", "petrochemical", "refineries", "wind_energy"],
    powerSource: "electric",
    rentalFit: "high",
    notes: ["Data logging capable.", "Verify hazardous-area suitability before use."],
    accuracyPriorityFit: "critical"
  },
  // RAD Pneumatic Series
  {
    id: "rad-pneumatic-300",
    name: "RAD Pneumatic 300",
    category: "pneumatic_torque_tool",
    torqueRange: { min: 100, max: 300 },
    accuracy: "±5%",
    weightClass: "medium",
    typicalApplications: ["wheel_nuts", "plant_maintenance"],
    industries: ["mining", "railway", "manufacturing"],
    powerSource: "air",
    rentalFit: "high",
    notes: ["Not precision clamp-load tools.", "Requires stable air supply."],
    accuracyPriorityFit: "standard"
  },
  {
    id: "rad-pneumatic-600",
    name: "RAD Pneumatic 600",
    category: "pneumatic_torque_tool",
    torqueRange: { min: 200, max: 600 },
    accuracy: "±5%",
    weightClass: "medium",
    typicalApplications: ["wheel_nuts", "plant_maintenance"],
    industries: ["mining", "railway", "manufacturing"],
    powerSource: "air",
    rentalFit: "high",
    notes: ["Not precision clamp-load tools.", "Requires stable air supply."],
    accuracyPriorityFit: "standard"
  },
  {
    id: "rad-pneumatic-900",
    name: "RAD Pneumatic 900",
    category: "pneumatic_torque_tool",
    torqueRange: { min: 300, max: 900 },
    accuracy: "±5%",
    weightClass: "medium",
    typicalApplications: ["wheel_nuts", "plant_maintenance"],
    industries: ["mining", "railway", "manufacturing"],
    powerSource: "air",
    rentalFit: "high",
    notes: ["Not precision clamp-load tools.", "Requires stable air supply."],
    accuracyPriorityFit: "standard"
  },
  {
    id: "rad-pneumatic-1200",
    name: "RAD Pneumatic 1200",
    category: "pneumatic_torque_tool",
    torqueRange: { min: 400, max: 1200 },
    accuracy: "±5%",
    weightClass: "medium",
    typicalApplications: ["wheel_nuts", "plant_maintenance"],
    industries: ["mining", "railway", "manufacturing"],
    powerSource: "air",
    rentalFit: "high",
    notes: ["Not precision clamp-load tools.", "Requires stable air supply."],
    accuracyPriorityFit: "standard"
  },
  {
    id: "rad-pneumatic-2000",
    name: "RAD Pneumatic 2000",
    category: "pneumatic_torque_tool",
    torqueRange: { min: 700, max: 2000 },
    accuracy: "±5%",
    weightClass: "medium",
    typicalApplications: ["wheel_nuts", "plant_maintenance"],
    industries: ["mining", "railway", "manufacturing"],
    powerSource: "air",
    rentalFit: "high",
    notes: ["Not precision clamp-load tools.", "Requires stable air supply."],
    accuracyPriorityFit: "standard"
  },
  {
    id: "rad-pneumatic-3000",
    name: "RAD Pneumatic 3000",
    category: "pneumatic_torque_tool",
    torqueRange: { min: 1000, max: 3000 },
    accuracy: "±5%",
    weightClass: "medium",
    typicalApplications: ["wheel_nuts", "plant_maintenance"],
    industries: ["mining", "railway", "manufacturing"],
    powerSource: "air",
    rentalFit: "high",
    notes: ["Not precision clamp-load tools.", "Requires stable air supply."],
    accuracyPriorityFit: "standard"
  },
  {
    id: "rad-pneumatic-5000",
    name: "RAD Pneumatic 5000",
    category: "pneumatic_torque_tool",
    torqueRange: { min: 1500, max: 5000 },
    accuracy: "±5%",
    weightClass: "medium",
    typicalApplications: ["wheel_nuts", "plant_maintenance"],
    industries: ["mining", "railway", "manufacturing"],
    powerSource: "air",
    rentalFit: "high",
    notes: ["Not precision clamp-load tools.", "Requires stable air supply."],
    accuracyPriorityFit: "standard"
  },
  {
    id: "rad-pneumatic-8000",
    name: "RAD Pneumatic 8000",
    category: "pneumatic_torque_tool",
    torqueRange: { min: 2500, max: 8000 },
    accuracy: "±5%",
    weightClass: "medium",
    typicalApplications: ["wheel_nuts", "plant_maintenance"],
    industries: ["mining", "railway", "manufacturing"],
    powerSource: "air",
    rentalFit: "high",
    notes: ["Not precision clamp-load tools.", "Requires stable air supply."],
    accuracyPriorityFit: "standard"
  },
  {
    id: "rad-pneumatic-11000",
    name: "RAD Pneumatic 11000",
    category: "pneumatic_torque_tool",
    torqueRange: { min: 4000, max: 11000 },
    accuracy: "±5%",
    weightClass: "medium",
    typicalApplications: ["wheel_nuts", "plant_maintenance"],
    industries: ["mining", "railway", "manufacturing"],
    powerSource: "air",
    rentalFit: "high",
    notes: ["Not precision clamp-load tools.", "Requires stable air supply."],
    accuracyPriorityFit: "standard"
  },
  // TorsionX Square Drive Series
  {
    id: "torsionx-sd-2",
    name: "TorsionX SD-2",
    category: "hydraulic_torque_wrench_square_drive",
    torqueRange: { min: 500, max: 2000 },
    accuracy: "±3%",
    weightClass: "heavy",
    typicalApplications: ["flange"],
    industries: ["oil_gas", "petrochemical", "refineries", "wind_energy", "mining"],
    powerSource: "hydraulic",
    rentalFit: "high",
    notes: ["Requires hydraulic pump system.", "Versatile reaction arm options."],
    accuracyPriorityFit: "high"
  },
  {
    id: "torsionx-sd-4",
    name: "TorsionX SD-4",
    category: "hydraulic_torque_wrench_square_drive",
    torqueRange: { min: 1000, max: 4000 },
    accuracy: "±3%",
    weightClass: "heavy",
    typicalApplications: ["flange"],
    industries: ["oil_gas", "petrochemical", "refineries", "wind_energy", "mining"],
    powerSource: "hydraulic",
    rentalFit: "high",
    notes: ["Requires hydraulic pump system.", "Versatile reaction arm options."],
    accuracyPriorityFit: "high"
  },
  {
    id: "torsionx-sd-8",
    name: "TorsionX SD-8",
    category: "hydraulic_torque_wrench_square_drive",
    torqueRange: { min: 2000, max: 8000 },
    accuracy: "±3%",
    weightClass: "heavy",
    typicalApplications: ["flange"],
    industries: ["oil_gas", "petrochemical", "refineries", "wind_energy", "mining"],
    powerSource: "hydraulic",
    rentalFit: "high",
    notes: ["Requires hydraulic pump system.", "Versatile reaction arm options."],
    accuracyPriorityFit: "high"
  },
  {
    id: "torsionx-sd-16",
    name: "TorsionX SD-16",
    category: "hydraulic_torque_wrench_square_drive",
    torqueRange: { min: 4000, max: 16000 },
    accuracy: "±3%",
    weightClass: "heavy",
    typicalApplications: ["flange"],
    industries: ["oil_gas", "petrochemical", "refineries", "wind_energy", "mining"],
    powerSource: "hydraulic",
    rentalFit: "high",
    notes: ["Requires hydraulic pump system.", "Versatile reaction arm options."],
    accuracyPriorityFit: "high"
  },
  {
    id: "torsionx-sd-32",
    name: "TorsionX SD-32",
    category: "hydraulic_torque_wrench_square_drive",
    torqueRange: { min: 8000, max: 32000 },
    accuracy: "±3%",
    weightClass: "heavy",
    typicalApplications: ["flange"],
    industries: ["oil_gas", "petrochemical", "refineries", "wind_energy", "mining"],
    powerSource: "hydraulic",
    rentalFit: "high",
    notes: ["Requires hydraulic pump system.", "Versatile reaction arm options."],
    accuracyPriorityFit: "high"
  },
  {
    id: "torsionx-sd-64",
    name: "TorsionX SD-64",
    category: "hydraulic_torque_wrench_square_drive",
    torqueRange: { min: 16000, max: 64000 },
    accuracy: "±3%",
    weightClass: "heavy",
    typicalApplications: ["flange"],
    industries: ["oil_gas", "petrochemical", "refineries", "wind_energy", "mining"],
    powerSource: "hydraulic",
    rentalFit: "high",
    notes: ["Requires hydraulic pump system.", "Versatile reaction arm options."],
    accuracyPriorityFit: "high"
  },
  // TorsionX Low Profile Cassette Series
  {
    id: "torsionx-lp-2",
    name: "TorsionX LP-2",
    category: "hydraulic_torque_wrench_cassette",
    torqueRange: { min: 500, max: 2000 },
    accuracy: "±3%",
    weightClass: "heavy",
    typicalApplications: ["flange", "shutdown_turnaround"],
    industries: ["petrochemical", "refineries", "oil_gas"],
    powerSource: "hydraulic",
    rentalFit: "high",
    notes: ["Minimal clearance.", "Requires cassette sizing."],
    accuracyPriorityFit: "high"
  },
  {
    id: "torsionx-lp-4",
    name: "TorsionX LP-4",
    category: "hydraulic_torque_wrench_cassette",
    torqueRange: { min: 1000, max: 4000 },
    accuracy: "±3%",
    weightClass: "heavy",
    typicalApplications: ["flange", "shutdown_turnaround"],
    industries: ["petrochemical", "refineries", "oil_gas"],
    powerSource: "hydraulic",
    rentalFit: "high",
    notes: ["Minimal clearance.", "Requires cassette sizing."],
    accuracyPriorityFit: "high"
  },
  {
    id: "torsionx-lp-8",
    name: "TorsionX LP-8",
    category: "hydraulic_torque_wrench_cassette",
    torqueRange: { min: 2000, max: 8000 },
    accuracy: "±3%",
    weightClass: "heavy",
    typicalApplications: ["flange", "shutdown_turnaround"],
    industries: ["petrochemical", "refineries", "oil_gas"],
    powerSource: "hydraulic",
    rentalFit: "high",
    notes: ["Minimal clearance.", "Requires cassette sizing."],
    accuracyPriorityFit: "high"
  },
  {
    id: "torsionx-lp-16",
    name: "TorsionX LP-16",
    category: "hydraulic_torque_wrench_cassette",
    torqueRange: { min: 4000, max: 16000 },
    accuracy: "±3%",
    weightClass: "heavy",
    typicalApplications: ["flange", "shutdown_turnaround"],
    industries: ["petrochemical", "refineries", "oil_gas"],
    powerSource: "hydraulic",
    rentalFit: "high",
    notes: ["Minimal clearance.", "Requires cassette sizing."],
    accuracyPriorityFit: "high"
  },
  {
    id: "torsionx-lp-32",
    name: "TorsionX LP-32",
    category: "hydraulic_torque_wrench_cassette",
    torqueRange: { min: 8000, max: 32000 },
    accuracy: "±3%",
    weightClass: "heavy",
    typicalApplications: ["flange", "shutdown_turnaround"],
    industries: ["petrochemical", "refineries", "oil_gas"],
    powerSource: "hydraulic",
    rentalFit: "high",
    notes: ["Minimal clearance.", "Requires cassette sizing."],
    accuracyPriorityFit: "high"
  },
  {
    id: "hydraulic-tensioner",
    name: "Hydraulic Bolt Tensioner System",
    category: "hydraulic_bolt_tensioner",
    torqueRange: { min: 1200, max: 30000 },
    accuracy: "±3% typical",
    weightClass: "heavy",
    typicalApplications: ["flange", "turbine", "shutdown_turnaround"],
    industries: ["aerospace", "wind_energy", "refineries", "oil_gas"],
    powerSource: "hydraulic",
    rentalFit: "high",
    notes: ["Clamp-load-first philosophy for critical joints. Requires stud protrusion and matched tooling for tensioning."],
    accuracyPriorityFit: "critical"
  }
];
